x-images:
  django: &django
    image: geotrek
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
      args:
        BASE_IMAGE: ubuntu:jammy
    user: ${UID:-1000}:${GID:-1000}
    env_file:
      - .env
    volumes:
      - .:/opt/geotrek-admin

services:
  postgres:
    image: my-pgrouting:latest
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - hiking-alerts_geotrek-network

  convertit:
    image: my-convertit:latest
    networks:
      - hiking-alerts_geotrek-network

  screamshotter:
    image: my-screamshotter:latest
    networks:
      - hiking-alerts_geotrek-network

  celery:
    <<: [ *django ]
    depends_on:
      - postgres
    command: celery -A geotrek worker -c 1
    networks:
      - hiking-alerts_geotrek-network

  web:
    <<: [ *django ]
    depends_on:
      - postgres
      - screamshotter
      - convertit
      - celery
    networks:
      - hiking-alerts_geotrek-network

  sphinx:
    <<: [ *django ]
    working_dir: /opt/geotrek-admin/docs
    command: sphinx-autobuild -b html --host 0.0.0.0 --port 8800 ./ ./_build/html
    networks:
      - hiking-alerts_geotrek-network

  geotrek-db-service:
    image: geotrek-db-service
    networks:
      - hiking-alerts_geotrek-network
      - hiking-alerts_pass-network

networks:
  hiking-alerts_geotrek-network:
    external: true
  hiking-alerts_pass-network:
    external: true

volumes:
  postgres: