name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f ./src/Dockerfile -t ghcr.io/${{ github.actor }}/hikealerts-springboot:latest ./src

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.actor }}/hikealerts-springboot:latest