name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot app
        run: |
          cd spring-boot  # Change to the subdirectory
          mvn clean package  # Build the Spring Boot app

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx build --platform linux/amd64,linux/arm64 -f ./spring-boot/Dockerfile --push -t ghcr.io/${{ github.actor }}/hikealerts-springboot:latest ./spring-boot